backend:
  name: git-gateway
  branch: master
local_backend: true
publish_mode: editorial_workflow
media_folder: 'images'
public_folder: '/img'
collections:
  - name: 'blog-page'
    label: 'Blog Page'
    folder: 'pages/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    sortable_fields:
      fields:
        - title
        - date
      default:
        field: date
        direction: Descending
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Draft'
        name: 'draft'
        widget: 'boolean'
        default: true
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
      - label: 'Tags'
        name: 'tags'
        widget: 'list'
        fields:
          - name: tag
            label: Tag
            widget: string
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
  - name: 'link'
    label: 'Link of Note'
    folder: 'pages/link'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    sortable_fields:
      fields:
        - title
        - date
      default:
        field: date
        direction: Descending
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Draft'
        name: 'draft'
        widget: 'boolean'
        default: true
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
      - label: 'Tags'
        name: 'tags'
        widget: 'list'
        fields:
          - name: tag
            label: Tag
            widget: string
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
  - name: 'til'
    label: 'Today I Learned'
    folder: 'pages/til'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    sortable_fields:
      fields:
        - title
        - date
      default:
        field: date
        direction: Descending
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Draft'
        name: 'draft'
        widget: 'boolean'
        default: true
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
      - label: 'Tags'
        name: 'tags'
        widget: 'list'
        fields:
          - name: tag
            label: Tag
            widget: string
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
